# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 778)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 210, 881, 101))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(10, 310, 881, 461))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 194))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.wealthInput = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.wealthInput.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.wealthInput.setFont(font)
        self.wealthInput.setObjectName("wealthInput")
        self.gridLayout.addWidget(self.wealthInput, 2, 1, 1, 1)
        self.leverageInput = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.leverageInput.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.leverageInput.setFont(font)
        self.leverageInput.setObjectName("leverageInput")
        self.leverageInput.addItem("")
        self.leverageInput.addItem("")
        self.leverageInput.addItem("")
        self.leverageInput.addItem("")
        self.leverageInput.addItem("")
        self.leverageInput.addItem("")
        self.gridLayout.addWidget(self.leverageInput, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cryptoInput = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.cryptoInput.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.cryptoInput.setFont(font)
        self.cryptoInput.setObjectName("cryptoInput")
        self.gridLayout.addWidget(self.cryptoInput, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.returnInput = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.returnInput.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.returnInput.setFont(font)
        self.returnInput.setEditable(True)
        self.returnInput.setObjectName("returnInput")
        self.returnInput.addItem("")
        self.gridLayout.addWidget(self.returnInput, 0, 1, 1, 1)
        self.returnButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.gridLayout.addWidget(self.returnButton, 0, 3, 1, 1)
        self.cryptoButtom = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.cryptoButtom.setFont(font)
        self.cryptoButtom.setObjectName("cryptoButtom")
        self.gridLayout.addWidget(self.cryptoButtom, 1, 2, 1, 1)
        self.orderButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.orderButton_2.setFont(font)
        self.orderButton_2.setObjectName("orderButton_2")
        self.gridLayout.addWidget(self.orderButton_2, 3, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(630, 10, 261, 191))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(0, 20, 261, 171))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setItalic(False)
        item.setFont(font)
        icon = QtGui.QIcon.fromTheme("1")
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times")
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times")
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times")
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times")
        item.setFont(font)
        self.listWidget.addItem(item)

        self.retranslateUi(Form)
        self.comboBox_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FTX資金費率套利策略-下單系統"))
        self.leverageInput.setItemText(0, _translate("Form", "1"))
        self.leverageInput.setItemText(1, _translate("Form", "2"))
        self.leverageInput.setItemText(2, _translate("Form", "3"))
        self.leverageInput.setItemText(3, _translate("Form", "5"))
        self.leverageInput.setItemText(4, _translate("Form", "10"))
        self.leverageInput.setItemText(5, _translate("Form", "20"))
        self.comboBox.setItemText(0, _translate("Form", "USDT"))
        self.comboBox.setItemText(1, _translate("Form", "USD"))
        self.label_3.setText(_translate("Form", "資金"))
        self.label_5.setText(_translate("Form", "槓桿倍數"))
        self.label.setText(_translate("Form", "年報酬率高於"))
        self.label_2.setText(_translate("Form", "特定標的"))
        self.label_4.setText(_translate("Form", "按"))
        self.comboBox_2.setCurrentText(_translate("Form", "年化報酬率"))
        self.comboBox_2.setItemText(0, _translate("Form", "last"))
        self.comboBox_2.setItemText(1, _translate("Form", "年化報酬率"))
        self.comboBox_2.setItemText(2, _translate("Form", "連續年化"))
        self.comboBox_2.setItemText(3, _translate("Form", "近一個月年化報酬率"))
        self.comboBox_2.setItemText(4, _translate("Form", "正連續"))
        self.comboBox_2.setItemText(5, _translate("Form", "負連續"))
        self.comboBox_2.setItemText(6, _translate("Form", "換手頻率"))
        self.comboBox_2.setItemText(7, _translate("Form", "可當保證金"))
        self.comboBox_2.setItemText(8, _translate("Form", "負"))
        self.comboBox_2.setItemText(9, _translate("Form", "正"))
        self.comboBox_2.setItemText(10, _translate("Form", "總時數"))
        self.comboBox_2.setItemText(11, _translate("Form", "正％"))
        self.comboBox_2.setItemText(12, _translate("Form", "負％"))
        self.comboBox_2.setItemText(13, _translate("Form", "volume"))
        self.comboBox_2.setItemText(14, _translate("Form", "有USDT現貨交易對"))
        self.comboBox_2.setItemText(15, _translate("Form", "有USD現貨交易對"))
        self.comboBox_2.setItemText(16, _translate("Form", "next_rate"))
        self.comboBox_2.setItemText(17, _translate("Form", "換手頻率/總時數"))
        self.label_9.setText(_translate("Form", "排序"))
        self.returnInput.setItemText(0, _translate("Form", "中位數"))
        self.returnButton.setText(_translate("Form", "篩選標的"))
        self.cryptoButtom.setText(_translate("Form", "選擇標的"))
        self.orderButton_2.setText(_translate("Form", "下單"))
        self.groupBox.setTitle(_translate("Form", "篩選條件"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", " -「換手頻率/總時數」小於中位數"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "-「總時數」大於第一四分位數（取值大的前75%）"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "-「過去24小時交易量」大於1,000,000"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "-「下期資金費率」正"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "- 必須有現貨交易對"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

